#!/bin/bash

# Java
export JAVA_HOME=/usr/lib/jvm/java-7-oracle
export JDK_HOME=$JAVA_HOME

# Servlet (for Jease)
export SERVLET_API=~/jease-marea-site/lib/servlet-api.jar

# GMSEC
export GMSEC_PLATFORM=linux.x86_64
export GMSEC_HOME=~/GMSEC_API-3.5
export LD_LIBRARY_PATH=$GMSEC_HOME/bin

# ROS
if [ -f /opt/ros/fuerte/setup.bash ]; then
	source /opt/ros/fuerte/setup.bash
	export ROS_PACKAGE_PATH=~/ros_workspace:$ROS_PACKAGE_PATH
	export ROS_WORKSPACE=~/ros_workspace
	export ROS_HOSTNAME=localhost
	export ROS_MASTER_URI=http://localhost:11311
fi

# Docker
dockps()  {
  docker ps ${@:2} | awk '
  NR==1{
    FIRSTLINEWIDTH=length($0)
    IDPOS=index($0,"CONTAINER ID");
    IMAGEPOS=index($0,"IMAGE");
    COMMANDPOS=index($0,"COMMAND");
    CREATEDPOS=index($0,"CREATED");
    STATUSPOS=index($0,"STATUS");
    PORTSPOS=index($0,"PORTS");
    NAMESPOS=index($0,"NAMES");
    UPDATECOL();
  }
  function UPDATECOL () {
    ID=substr($0,IDPOS,IMAGEPOS-IDPOS-1);
    IMAGE=substr($0,IMAGEPOS,COMMANDPOS-IMAGEPOS-1);
    COMMAND=substr($0,COMMANDPOS,CREATEDPOS-COMMANDPOS-1);
    CREATED=substr($0,CREATEDPOS,STATUSPOS-CREATEDPOS-1);
    STATUS=substr($0,STATUSPOS,PORTSPOS-STATUSPOS-1);
    PORTS=substr($0,PORTSPOS,NAMESPOS-PORTSPOS-1);
    NAMES=substr($0, NAMESPOS);
  }
  function PRINT () {
    print '"${1//|/ }"';
  }
  NR==2{
    NAMES=sprintf("%s%*s",NAMES,length($0)-FIRSTLINEWIDTH,"");
    PRINT();
  }
  NR>1{
    UPDATECOL();
    PRINT();
  }' | less -FSX;
}
dps() { dockps "NAMES|IMAGE|STATUS|CREATED|COMMAND" $@; }
dpsa() { dps -a $@; }
dports() { dockps "NAMES|PORTS" $@; }
dtail() { docker logs --tail=10 $@; }
